### ISSUE TITLE
Hỏi về động cơ chơi cờ tướng

### ISSUE THREAD

**Issue by huynq55** [nguyenpham/FirstChess#1]
Cháu chào bác Nguyên. Cháu được biết bác là tác giả động cơ chơi cờ tướng sao la, VSCCP, và mới đây là bài viết của bác trên diễn đàn Thăng Long Kỳ Đạo về phần mềm cờ tướng bác mới viết.
Cháu cũng muốn lập trình phần mềm cờ tướng nhưng không tìm được người thầy nào hướng dẫn chỉ dạy, tài liệu về lập trình phần mềm cờ tướng lại có rất ít ở trên mạng. Cháu mong muốn viết được một động cơ chơi cờ mã nguồn mở, và làm tutorial để hướng dẫn các bạn khác lập trình. Vậy nên cháu muốn tham khảo kinh nghiệm từ người đi trước là bác ạ.
Cháu muốn viết dài nhưng không biết bác có đọc được không nên cháu chỉ viết đến đây thôi. Cháu không biết liên hệ với bác bằng cách nào nên đành lập issue này để liên hệ với bác. Mong nhận được phản hồi của bác.
@nguyenpham

**Comment by nguyenpham** [comment]
Bạn PM cho tôi bên TLKĐ tôi sẽ trả lời. Repo này chỉ dành cho chess và những thứ liên quan đến FirstChess. Thanks

Closed due to out of topic.
